name: Release

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main

jobs:
  release:
    name: Release
    # Only run if CI was successful and we're on main branch, or if manually triggered
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main')
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Head branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Head SHA: ${{ github.event.workflow_run.head_sha }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for semantic-release
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: Debug Git Status
        run: |
          git branch --show-current
          git rev-parse HEAD

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.1'

      - name: Debug Node Version
        run: |
          echo "Node version:"
          node --version
          echo "NPM version:"
          npm --version
          which node
          echo "Node path:"
          echo $PATH

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8'
          run_install: false

      - name: Debug pnpm Node Version
        run: |
          echo "pnpm Node version:"
          pnpm node -v
          echo "pnpm info:"
          pnpm config list
          echo "which node (from pnpm):"
          pnpm exec which node
          echo "Node version after pnpm:"
          node -v

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Verify Node Version Again
        run: |
          echo "Final Node version check:"
          node --version
          which node

      - name: Configure Git User
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        run: |
          echo "Starting release process..."
          npx semantic-release
